# Generated by Django 3.1.6 on 2021-02-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_auto_20210208_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='numbers_of_players',
            new_name='number_of_players',
        ),
    ]
